export const mockProducts = [
  {
    id: '1',
    name: 'Tepung Singkong',
    category: 'Bahan Baku',
    seller: 'Berkah Jaya',
    price: 12000,
    unit: 'kg',
    minOrder: '25 kg',
    location: 'Bekasi',
    distance: 15,
    image: '/logo.png',
  },
  {
    id: '2',
    name: 'Gula Aren Organik',
    category: 'Bahan Baku',
    seller: 'Koperasi Tani Makmur',
    price: 25000,
    unit: 'kg',
    minOrder: '50 kg',
    location: 'Bogor',
    distance: 12,
    image: '/logo.png',
  },
  {
    id: '3',
    name: 'Botol Kaca 500ml',
    category: 'Kemasan',
    seller: 'CV. Kemasan Jaya',
    price: 12000,
    unit: 'kg',
    minOrder: '50 kg',
    location: 'Depok',
    distance: 8,
    image: '/logo.png',
  },
  {
    id: '4',
    name: 'Minyak Kelapa Murni',
    category: 'Bahan Baku',
    seller: 'Toko Herbal Nusantara',
    price: 35000,
    unit: 'liter',
    minOrder: '20 liter',
    location: 'Tangerang',
    distance: 18,
    image: '/logo.png',
  },
  {
    id: '5',
    name: 'Karton Dus 20x20cm',
    category: 'Kemasan',
    seller: 'PT. Packaging Indo',
    price: 5000,
    unit: 'pcs',
    minOrder: '100 pcs',
    location: 'Jakarta Barat',
    distance: 22,
    image: '/logo.png',
  },
  {
    id: '6',
    name: 'Kacang Tanah Kupas',
    category: 'Bahan Baku',
    seller: 'Gudang Kacang Sentosa',
    price: 18000,
    unit: 'kg',
    minOrder: '30 kg',
    location: 'Cibinong',
    distance: 10,
    image: '/logo.png',
  },
  {
    id: '7',
    name: 'Label Stiker Custom',
    category: 'Kemasan',
    seller: 'Digital Print Express',
    price: 2500,
    unit: 'pcs',
    minOrder: '500 pcs',
    location: 'Jakarta Selatan',
    distance: 25,
    image: '/logo.png',
  },
  {
    id: '8',
    name: 'Tepung Terigu Premium',
    category: 'Bahan Baku',
    seller: 'Toko Roti Bahagia',
    price: 14000,
    unit: 'kg',
    minOrder: '40 kg',
    location: 'Bekasi',
    distance: 16,
    image: '/logo.png',
  },
];
