export const mockProducts = [
  {
    id: '1',
    name: 'Tepung Singkong',
    category: 'Bahan Baku',
    seller: 'Berkah Jaya',
    price: 12000,
    unit: 'kg',
    minOrder: '25kg',
    location: 'Bekasi',
    distance: 15,
    image: '/logo.png',
  },
  {
    id: '2',
    name: 'Gula Aren Organik',
    category: 'Bahan Baku',
    seller: 'Koperasi Tani Makmur',
    price: 25000,
    unit: 'kg',
    minOrder: '50kg',
    location: 'Bogor',
    distance: 12,
    image: '/logo.png',
  },
  {
    id: '3',
    name: 'Botol Kaca 500ml',
    category: 'Kemasan',
    seller: 'CV. Kemasan Jaya',
    price: 12000,
    unit: 'kg',
    minOrder: '50kg',
    location: 'Depok',
    distance: 8,
    image: '/logo.png',
  },
];
