export const mockProducts = [
  {
    id: '1',
    name: 'Tepung Singkong',
    category: 'Bahan Baku',
    seller: 'Berkah Jaya',
    price: 12000,
    unit: 'kg',
    minOrder: '25 kg',
    location: 'Bekasi',
    distance: 15,
    image: '/logo.png',
  },
  {
    id: '2',
    name: 'Gula Aren Organik',
    category: 'Bahan Baku',
    seller: 'Koperasi Tani Makmur',
    price: 25000,
    unit: 'kg',
    minOrder: '50 kg',
    location: 'Bogor',
    distance: 12,
    image: '/logo.png',
  },
  {
    id: '3',
    name: 'Botol Kaca 500ml',
    category: 'Kemasan',
    seller: 'CV. Kemasan Jaya',
    price: 12000,
    unit: 'kg',
    minOrder: '50 kg',
    location: 'Depok',
    distance: 8,
    image: '/logo.png',
  },
  {
    id: '4',
    name: 'Minyak Kelapa Murni',
    category: 'Bahan Baku',
    seller: 'Toko Herbal Nusantara',
    price: 35000,
    unit: 'liter',
    minOrder: '20 liter',
    location: 'Tangerang',
    distance: 18,
    image: '/logo.png',
  },
  {
    id: '5',
    name: 'Karton Dus 20x20cm',
    category: 'Kemasan',
    seller: 'PT. Packaging Indo',
    price: 5000,
    unit: 'pcs',
    minOrder: '100 pcs',
    location: 'Jakarta Barat',
    distance: 22,
    image: '/logo.png',
  },
  {
    id: '6',
    name: 'Kacang Tanah Kupas',
    category: 'Bahan Baku',
    seller: 'Gudang Kacang Sentosa',
    price: 18000,
    unit: 'kg',
    minOrder: '30 kg',
    location: 'Cibinong',
    distance: 10,
    image: '/logo.png',
  },
  {
    id: '7',
    name: 'Label Stiker Custom',
    category: 'Kemasan',
    seller: 'Digital Print Express',
    price: 2500,
    unit: 'pcs',
    minOrder: '500 pcs',
    location: 'Jakarta Selatan',
    distance: 25,
    image: '/logo.png',
  },
  {
    id: '8',
    name: 'Tepung Terigu Premium',
    category: 'Bahan Baku',
    seller: 'Toko Roti Bahagia',
    price: 14000,
    unit: 'kg',
    minOrder: '40 kg',
    location: 'Bekasi',
    distance: 16,
    image: '/logo.png',
  },
  {
    id: '9',
    name: 'Madu Hutan Asli',
    category: 'Bahan Baku',
    seller: 'Lebah Emas Farm',
    price: 120000,
    unit: 'kg',
    minOrder: '5 kg',
    location: 'Sukabumi',
    distance: 45,
    image: '/logo.png',
  },
  {
    id: '10',
    name: 'Plastik Wrap Roll',
    category: 'Kemasan',
    seller: 'Indo Plastik Sentral',
    price: 85000,
    unit: 'roll',
    minOrder: '10 roll',
    location: 'Karawang',
    distance: 35,
    image: '/logo.png',
  },
  {
    id: '11',
    name: 'Beras Organik Premium',
    category: 'Bahan Baku',
    seller: 'Sawah Hijau Cooperative',
    price: 22000,
    unit: 'kg',
    minOrder: '25 kg',
    location: 'Cianjur',
    distance: 50,
    image: '/logo.png',
  },
  {
    id: '12',
    name: 'Kemasan Pouch Aluminium',
    category: 'Kemasan',
    seller: 'Flexible Packaging Co',
    price: 3500,
    unit: 'pcs',
    minOrder: '200 pcs',
    location: 'Bandung',
    distance: 180,
    image: '/logo.png',
  },
  {
    id: '13',
    name: 'Garam Laut Kristal',
    category: 'Bahan Baku',
    seller: 'Garam Nusantara',
    price: 8000,
    unit: 'kg',
    minOrder: '50 kg',
    location: 'Serang',
    distance: 65,
    image: '/logo.png',
  },
  {
    id: '14',
    name: 'Tutup Botol Aluminium',
    category: 'Kemasan',
    seller: 'Cap & Closure Indonesia',
    price: 1200,
    unit: 'pcs',
    minOrder: '1000 pcs',
    location: 'Jakarta Utara',
    distance: 28,
    image: '/logo.png',
  },
  {
    id: '15',
    name: 'Tepung Jagung Organik',
    category: 'Bahan Baku',
    seller: 'Jagung Manis Farm',
    price: 16000,
    unit: 'kg',
    minOrder: '20 kg',
    location: 'Purwakarta',
    distance: 55,
    image: '/logo.png',
  },
];
