// This file is auto-generated by @hey-api/openapi-ts

export const StoreSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
    },
    userId: {
      type: 'string',
    },
    storeName: {
      type: 'string',
      nullable: true,
    },
    businessId: {
      type: 'string',
      nullable: true,
    },
    businessType: {
      type: 'string',
      nullable: true,
    },
    businessDescription: {
      type: 'string',
      nullable: true,
    },
    tags: {
      type: 'array',
      nullable: true,
      items: {
        type: 'string',
      },
    },
    description: {
      type: 'string',
      nullable: true,
    },
    phoneNumber: {
      type: 'string',
      nullable: true,
    },
    address: {
      type: 'string',
      nullable: true,
    },
    city: {
      type: 'string',
      nullable: true,
    },
    province: {
      type: 'string',
      nullable: true,
    },
    postalCode: {
      type: 'string',
      nullable: true,
    },
    createdAt: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'string',
          format: 'date',
        },
      ],
    },
    updatedAt: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'string',
          format: 'date',
        },
      ],
    },
  },
  required: [
    'id',
    'userId',
    'storeName',
    'businessId',
    'businessType',
    'businessDescription',
    'tags',
    'description',
    'phoneNumber',
    'address',
    'city',
    'province',
    'postalCode',
    'createdAt',
    'updatedAt',
  ],
} as const;

export const ProductSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
    },
    name: {
      type: 'string',
      nullable: true,
    },
    description: {
      type: 'string',
      nullable: true,
    },
    price: {
      type: 'integer',
      nullable: true,
      minimum: -2147483648,
      maximum: 2147483647,
    },
    imageUrls: {
      type: 'array',
      nullable: true,
      items: {
        type: 'string',
      },
    },
    unit: {
      type: 'string',
      nullable: true,
    },
    stock: {
      type: 'integer',
      nullable: true,
      minimum: -2147483648,
      maximum: 2147483647,
    },
    tags: {
      type: 'array',
      nullable: true,
      items: {
        type: 'string',
      },
    },
    storeId: {
      type: 'string',
    },
    createdAt: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'string',
          format: 'date',
        },
      ],
    },
  },
  required: [
    'id',
    'name',
    'description',
    'price',
    'imageUrls',
    'unit',
    'stock',
    'tags',
    'storeId',
    'createdAt',
  ],
} as const;

export const WholesalePriceSchema = {
  type: 'object',
  properties: {
    id: {
      type: 'string',
    },
    productId: {
      type: 'string',
    },
    minQuantity: {
      type: 'integer',
      nullable: true,
      minimum: -2147483648,
      maximum: 2147483647,
    },
    maxQuantity: {
      type: 'integer',
      nullable: true,
      minimum: -2147483648,
      maximum: 2147483647,
    },
    price: {
      type: 'integer',
      nullable: true,
      minimum: -2147483648,
      maximum: 2147483647,
    },
  },
  required: ['id', 'productId', 'minQuantity', 'maxQuantity', 'price'],
} as const;

export const ProductWithStoreSchema = {
  allOf: [
    {
      $ref: '#/components/schemas/Product',
    },
    {
      type: 'object',
      properties: {
        store: {
          $ref: '#/components/schemas/Store',
        },
        wholesalePrices: {
          type: 'array',
          items: {
            $ref: '#/components/schemas/WholesalePrice',
          },
        },
      },
    },
  ],
} as const;
