// This file is auto-generated by @hey-api/openapi-ts
import type { HealthResponse, ProtectedhealthResponse } from './types.gen';

export const healthResponseTransformer = async (
  data: any,
): Promise<HealthResponse> => {
  if (data.data) {
    data.data.timestamp = new Date(data.data.timestamp);
  }
  return data;
};

export const protectedhealthResponseTransformer = async (
  data: any,
): Promise<ProtectedhealthResponse> => {
  if (data.data) {
    if (data.data.user) {
      data.data.user.createdAt = new Date(data.data.user.createdAt);
      data.data.user.updatedAt = new Date(data.data.user.updatedAt);
    }
    if (data.data.session) {
      data.data.session.expiresAt = new Date(data.data.session.expiresAt);
      data.data.session.createdAt = new Date(data.data.session.createdAt);
      data.data.session.updatedAt = new Date(data.data.session.updatedAt);
    }
    data.data.timestamp = new Date(data.data.timestamp);
  }
  return data;
};
