import { CollaborationData, Product } from '@/types/page/collaboration';

// Mock data for collaborations
export const mockCollaborations: CollaborationData[] = [
  {
    id: '1',
    title: 'Beli Bareng Gula Aren Premium',
    initiator: 'CV. Makanan Sehat',
    status: 'Aktif' as const,
    progress: 70, // 350/500
    currentAmount: 350,
    targetAmount: 500,
    unit: 'kg',
    participantsCount: 5,
    participantsText: '5 UMKM bergabung',
    savingsPercentage: 25,
    borderColor: 'border-green-400',
    statusColor: 'bg-green-100 text-green-700',
  },
  {
    id: '3',
    title: 'Beli Bareng Bahan Kemasan Ramah Lingkungan',
    initiator: 'Green Pack Indonesia',
    status: 'Aktif' as const,
    progress: 45, // 450/1000
    currentAmount: 450,
    targetAmount: 1000,
    unit: 'pcs',
    participantsCount: 8,
    participantsText: '8 UMKM bergabung',
    savingsPercentage: 30,
    borderColor: 'border-green-400',
    statusColor: 'bg-green-100 text-green-700',
  },
  {
    id: '7',
    title: 'Beli Bareng Tepung Terigu Premium',
    initiator: 'Roti Bahagia',
    status: 'Aktif' as const,
    progress: 85, // 850/1000
    currentAmount: 850,
    targetAmount: 1000,
    unit: 'kg',
    participantsCount: 6,
    participantsText: '6 UMKM bergabung',
    savingsPercentage: 18,
    borderColor: 'border-green-400',
    statusColor: 'bg-green-100 text-green-700',
  },
  {
    id: '2',
    title: 'Kolaborasi Produk Hampers',
    initiator: 'Toko Oleh-oleh Nusa',
    status: 'Perencanaan' as const,
    description:
      'Mencari mitra untuk produksi hampers lebaran: kerupuk, dodol, kue kering',
    participantsCount: 3,
    participantsText: '3 UMKM tertarik',
    borderColor: 'border-blue-400',
    statusColor: 'bg-blue-100 text-blue-700',
    hasJoinButton: true,
  },
  {
    id: '4',
    title: 'Kolaborasi Event Pameran Produk Lokal',
    initiator: 'Komunitas Kreatif Lokal',
    status: 'Perencanaan' as const,
    description:
      'Mengadakan pameran bersama untuk mempromosikan produk UMKM lokal di mall',
    participantsCount: 12,
    participantsText: '12 UMKM tertarik',
    borderColor: 'border-blue-400',
    statusColor: 'bg-blue-100 text-blue-700',
    hasJoinButton: true,
  },
  {
    id: '6',
    title: 'Kolaborasi Platform Digital Marketing',
    initiator: 'Digital Marketing Hub',
    status: 'Perencanaan' as const,
    description:
      'Bergabung untuk paket pemasaran digital yang lebih terjangkau dengan social media management',
    participantsCount: 7,
    participantsText: '7 UMKM tertarik',
    borderColor: 'border-blue-400',
    statusColor: 'bg-blue-100 text-blue-700',
    hasJoinButton: true,
  },
  {
    id: '8',
    title: 'Kolaborasi Pelatihan Keuangan UMKM',
    initiator: 'Lembaga Pelatihan Bisnis',
    status: 'Perencanaan' as const,
    description:
      'Program pelatihan manajemen keuangan dan akuntansi sederhana untuk UMKM',
    participantsCount: 20,
    participantsText: '20 UMKM tertarik',
    borderColor: 'border-blue-400',
    statusColor: 'bg-blue-100 text-blue-700',
    hasJoinButton: true,
  },
  {
    id: '5',
    title: 'Beli Bareng Minyak Goreng Curah',
    initiator: 'Warung Makan Berkah',
    status: 'Selesai' as const,
    progress: 100, // 2000/2000
    currentAmount: 2000,
    targetAmount: 2000,
    unit: 'liter',
    participantsCount: 15,
    participantsText: '15 UMKM bergabung',
    savingsPercentage: 20,
    borderColor: 'border-gray-400',
    statusColor: 'bg-gray-100 text-gray-700',
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Gula Aren Premium',
    category: 'Bahan Baku',
    description: 'Gula aren organik berkualitas tinggi untuk produksi makanan',
    unit: 'kg',
    estimatedPrice: 15000,
    targetAmount: 500,
    savingsPercentage: 25,
  },
  {
    id: '2',
    name: 'Kemasan Hampers',
    category: 'Kemasan',
    description: 'Paket kemasan untuk produk hampers lebaran',
    unit: 'set',
    estimatedPrice: 25000,
    targetAmount: 100,
    savingsPercentage: 30,
  },
  {
    id: '3',
    name: 'Tepung Tapioka',
    category: 'Bahan Baku',
    description: 'Tepung tapioka murni untuk berbagai produk olahan',
    unit: 'kg',
    estimatedPrice: 8000,
    targetAmount: 1000,
    savingsPercentage: 18,
  },
  {
    id: '4',
    name: 'Botol Kaca 500ml',
    category: 'Kemasan',
    description: 'Botol kaca food grade untuk minuman dan saus',
    unit: 'pcs',
    estimatedPrice: 5000,
    targetAmount: 2000,
    savingsPercentage: 20,
  },
];
